version: '3'

services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ../certs/conf:/etc/letsencrypt:ro
      - ../certs/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../certs/conf:/etc/letsencrypt:ro
      - ../certs/www:/var/www/certbot:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $${!}; done;'"